//////////////////////////////////////////////////////////////////////////////
// Name:        SVGAltGlyphElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_ALT_GLYPH_ELEMENT_H
#define WX_SVG_ALT_GLYPH_ELEMENT_H

#include "SVGTextPositioningElement.h"
#include "SVGURIReference.h"
#include "String_wxsvg.h"
#include "Element.h"

class wxSVGAltGlyphElement:
  public wxSVGTextPositioningElement,
  public wxSVGURIReference
{
  protected:
    std::wstring m_glyphRef;
    std::wstring m_format;

  public:
    inline const std::wstring& GetGlyphRef() const { return m_glyphRef; }
    inline void SetGlyphRef(const std::wstring& n) { m_glyphRef = n; }

    inline const std::wstring& GetFormat() const { return m_format; }
    inline void SetFormat(const std::wstring& n) { m_format = n; }

  public:
    wxSVGAltGlyphElement(std::wstring tagName = _T("altGlyph")):
      wxSVGTextPositioningElement(tagName) {}
    virtual ~wxSVGAltGlyphElement() {}
    wxSvgXmlNode* CloneNode(bool deep = true) { return new wxSVGAltGlyphElement(*this); }
    bool HasAttribute(const std::wstring& name);
    std::wstring GetAttribute(const std::wstring& name);
    bool SetAttribute(const std::wstring& name, const std::wstring& value);
    wxSvgXmlAttrHash GetAttributes() const;
    virtual wxSVGDTD GetDtd() const { return wxSVG_ALTGLYPH_ELEMENT; }
};

#endif // WX_SVG_ALT_GLYPH_ELEMENT_H
