//////////////////////////////////////////////////////////////////////////////
// Name:        SVGColorProfileElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_COLOR_PROFILE_ELEMENT_H
#define WX_SVG_COLOR_PROFILE_ELEMENT_H

#include "SVGElement.h"
#include "SVGURIReference.h"
#include "SVGRenderingIntent.h"
#include "String_wxsvg.h"
#include "Element.h"

class wxSVGColorProfileElement:
  public wxSVGElement,
  public wxSVGURIReference,
  public wxSVGRenderingIntent
{
  protected:
    std::wstring m_local;
    std::wstring m_name;
    wxRENDERING_INTENT m_renderingIntent;

  public:
    inline const std::wstring& GetLocal() const { return m_local; }
    inline void SetLocal(const std::wstring& n) { m_local = n; }

    inline const std::wstring& GetName() const { return m_name; }
    inline void SetName(const std::wstring& n) { m_name = n; }

    inline wxRENDERING_INTENT GetRenderingIntent() const { return m_renderingIntent; }
    inline void SetRenderingIntent(const wxRENDERING_INTENT& n) { m_renderingIntent = n; }

  public:
    wxSVGColorProfileElement(std::wstring tagName = _T("color-profile")):
      wxSVGElement(tagName), m_renderingIntent(wxRENDERING_INTENT(0)) {}
    virtual ~wxSVGColorProfileElement() {}
    wxSvgXmlNode* CloneNode(bool deep = true) { return new wxSVGColorProfileElement(*this); }
    bool HasAttribute(const std::wstring& name);
    std::wstring GetAttribute(const std::wstring& name);
    bool SetAttribute(const std::wstring& name, const std::wstring& value);
    wxSvgXmlAttrHash GetAttributes() const;
    virtual wxSVGDTD GetDtd() const { return wxSVG_COLOR_PROFILE_ELEMENT; }
};

#endif // WX_SVG_COLOR_PROFILE_ELEMENT_H
