//////////////////////////////////////////////////////////////////////////////
// Name:        SVGDocument.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_DOCUMENT_H
#define WX_SVG_DOCUMENT_H

class wxSVGSVGElement;
class wxSVGElement;
class wxSVGCanvas;

#include "Document.h"
#include "DocumentEvent.h"
#include "String_wxsvg.h"
#include "SVGRect.h"
#include "SVGMatrix.h"
#include "wxImage.h"


class wxSVGDocument:
  public wxSvgXmlDocument,
  public wxDocumentEvent
{
  protected:
    std::wstring m_title;
    std::wstring m_referrer;
    std::wstring m_domain;
    std::wstring m_URL;

  public:
    inline const std::wstring& GetTitle() const { return m_title; }
    inline void SetTitle(const std::wstring& n) { m_title = n; }

    inline const std::wstring& GetReferrer() const { return m_referrer; }
    inline void SetReferrer(const std::wstring& n) { m_referrer = n; }

    inline const std::wstring& GetDomain() const { return m_domain; }
    inline void SetDomain(const std::wstring& n) { m_domain = n; }

    inline const std::wstring& GetURL() const { return m_URL; }
    inline void SetURL(const std::wstring& n) { m_URL = n; }


  protected:
    wxSVGCanvas* m_canvas;
    double m_scale;
    double m_scaleY;

    wxSVGMatrix m_screenCTM;

    double m_time;
    double GetDuration(wxSVGElement* parent);
  public:
    wxSVGDocument() { Init(); }
    wxSVGDocument(const std::wstring& filename, const std::wstring& encoding = _T("UTF-8")):
      wxSvgXmlDocument(filename, encoding) { Init(); }
    wxSVGDocument(const wxSVGDocument& doc);
    virtual ~wxSVGDocument();
    
    void Init();
    inline wxSVGCanvas* GetCanvas() { return m_canvas; }
    inline double GetScale() { return m_scale; }
    inline double GetScaleX() { return m_scale; }
    inline double GetScaleY() { return m_scaleY > 0 ? m_scaleY : m_scale; }
    const wxSVGMatrix& GetScreenCTM() { return m_screenCTM; }
    
    wxSvgXmlElement* CreateElement(const std::wstring& tagName);
    wxSvgXmlElement* CreateElementNS(const std::wstring& namespaceURI, const std::wstring& qualifiedName);
    
    wxSVGSVGElement* GetRootElement() { return (wxSVGSVGElement*) GetRoot(); }
    void SetRootElement(wxSVGSVGElement* n) { SetRoot((wxSvgXmlElement*) n); }
    
    wxSVGElement* GetElementById(const std::wstring& id);
    
    double GetDuration();
    double _GetCurrentTime() { return m_time; }
    void SetCurrentTime(double seconds);
    
    wxImage Render(int width = -1, int height = -1, const wxSVGRect* rect = NULL, bool preserveAspectRatio = true,
		bool alpha = false);
    wxImage RenderElementById(const std::wstring& id);
  private:
      DECLARE_DYNAMIC_CLASS(wxSVGDocument)
};

#endif // WX_SVG_DOCUMENT_H
