//////////////////////////////////////////////////////////////////////////////
// Name:        SVGFontElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_FONT_ELEMENT_H
#define WX_SVG_FONT_ELEMENT_H

#include "SVGElement.h"
#include "SVGExternalResourcesRequired.h"
#include "SVGStylable.h"
#include "String_wxsvg.h"
#include "Element.h"

class wxSVGFontElement:
  public wxSVGElement,
  public wxSVGExternalResourcesRequired,
  public wxSVGStylable
{
  public:
    wxSVGFontElement(std::wstring tagName = _T("font")):
      wxSVGElement(tagName) {}
    virtual ~wxSVGFontElement() {}
    wxSvgXmlNode* CloneNode(bool deep = true) { return new wxSVGFontElement(*this); }
    bool HasAttribute(const std::wstring& name);
    std::wstring GetAttribute(const std::wstring& name);
    bool SetAttribute(const std::wstring& name, const std::wstring& value);
    wxSvgXmlAttrHash GetAttributes() const;
    virtual wxSVGDTD GetDtd() const { return wxSVG_FONT_ELEMENT; }
};

#endif // WX_SVG_FONT_ELEMENT_H
