//////////////////////////////////////////////////////////////////////////////
// Name:        SVGFEFuncGElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_FE_FUNC_G_ELEMENT_H
#define WX_SVG_FE_FUNC_G_ELEMENT_H

#include "SVGComponentTransferFunctionElement.h"
#include "String_wxsvg.h"
#include "Element.h"

class wxSVGFEFuncGElement:
  public wxSVGComponentTransferFunctionElement
{
  public:
    wxSVGFEFuncGElement(std::wstring tagName = _T("feFuncG")):
      wxSVGComponentTransferFunctionElement(tagName) {}
    virtual ~wxSVGFEFuncGElement() {}
    wxSvgXmlNode* CloneNode(bool deep = true) { return new wxSVGFEFuncGElement(*this); }
    bool HasAttribute(const std::wstring& name);
    std::wstring GetAttribute(const std::wstring& name);
    bool SetAttribute(const std::wstring& name, const std::wstring& value);
    wxSvgXmlAttrHash GetAttributes() const;
    virtual wxSVGDTD GetDtd() const { return wxSVG_FEFUNCG_ELEMENT; }
};

#endif // WX_SVG_FE_FUNC_G_ELEMENT_H
