//////////////////////////////////////////////////////////////////////////////
// Name:        SVGFontFaceSrcElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_FONT_FACE_SRC_ELEMENT_H
#define WX_SVG_FONT_FACE_SRC_ELEMENT_H

#include "SVGElement.h"
#include "String_wxsvg.h"
#include "Element.h"

class wxSVGFontFaceSrcElement:
  public wxSVGElement
{
  public:
    wxSVGFontFaceSrcElement(std::wstring tagName = _T("font-face-src")):
      wxSVGElement(tagName) {}
    virtual ~wxSVGFontFaceSrcElement() {}
    wxSvgXmlNode* CloneNode(bool deep = true) { return new wxSVGFontFaceSrcElement(*this); }
    bool HasAttribute(const std::wstring& name);
    std::wstring GetAttribute(const std::wstring& name);
    bool SetAttribute(const std::wstring& name, const std::wstring& value);
    wxSvgXmlAttrHash GetAttributes() const;
    virtual wxSVGDTD GetDtd() const { return wxSVG_FONT_FACE_SRC_ELEMENT; }
};

#endif // WX_SVG_FONT_FACE_SRC_ELEMENT_H
