//////////////////////////////////////////////////////////////////////////////
// Name:        SVGMPathElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_M_PATH_ELEMENT_H
#define WX_SVG_M_PATH_ELEMENT_H

#include "SVGElement.h"
#include "SVGURIReference.h"
#include "SVGExternalResourcesRequired.h"
#include "String_wxsvg.h"
#include "Element.h"

class wxSVGMPathElement:
  public wxSVGElement,
  public wxSVGURIReference,
  public wxSVGExternalResourcesRequired
{
  public:
    wxSVGMPathElement(std::wstring tagName = _T("mpath")):
      wxSVGElement(tagName) {}
    virtual ~wxSVGMPathElement() {}
    wxSvgXmlNode* CloneNode(bool deep = true) { return new wxSVGMPathElement(*this); }
    bool HasAttribute(const std::wstring& name);
    std::wstring GetAttribute(const std::wstring& name);
    bool SetAttribute(const std::wstring& name, const std::wstring& value);
    wxSvgXmlAttrHash GetAttributes() const;
    virtual wxSVGDTD GetDtd() const { return wxSVG_MPATH_ELEMENT; }
};

#endif // WX_SVG_M_PATH_ELEMENT_H
