//////////////////////////////////////////////////////////////////////////////
// Name:        SVGMetadataElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_METADATA_ELEMENT_H
#define WX_SVG_METADATA_ELEMENT_H

#include "SVGElement.h"
#include "String_wxsvg.h"
#include "Element.h"

class wxSVGMetadataElement:
  public wxSVGElement
{
  public:
    wxSVGMetadataElement(std::wstring tagName = _T("metadata")):
      wxSVGElement(tagName) {}
    virtual ~wxSVGMetadataElement() {}
    wxSvgXmlNode* CloneNode(bool deep = true) { return new wxSVGMetadataElement(*this); }
    bool HasAttribute(const std::wstring& name);
    std::wstring GetAttribute(const std::wstring& name);
    bool SetAttribute(const std::wstring& name, const std::wstring& value);
    wxSvgXmlAttrHash GetAttributes() const;
    virtual wxSVGDTD GetDtd() const { return wxSVG_METADATA_ELEMENT; }
};

#endif // WX_SVG_METADATA_ELEMENT_H
