//////////////////////////////////////////////////////////////////////////////
// Name:        SVGScriptElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_SCRIPT_ELEMENT_H
#define WX_SVG_SCRIPT_ELEMENT_H

#include "SVGElement.h"
#include "SVGURIReference.h"
#include "SVGExternalResourcesRequired.h"
#include "String_wxsvg.h"
#include "Element.h"

class wxSVGScriptElement:
  public wxSVGElement,
  public wxSVGURIReference,
  public wxSVGExternalResourcesRequired
{
  protected:
    std::wstring m_type;

  public:
    inline const std::wstring& GetType() const { return m_type; }
    inline void SetType(const std::wstring& n) { m_type = n; }

  public:
    wxSVGScriptElement(std::wstring tagName = _T("script")):
      wxSVGElement(tagName) {}
    virtual ~wxSVGScriptElement() {}
    wxSvgXmlNode* CloneNode(bool deep = true) { return new wxSVGScriptElement(*this); }
    bool HasAttribute(const std::wstring& name);
    std::wstring GetAttribute(const std::wstring& name);
    bool SetAttribute(const std::wstring& name, const std::wstring& value);
    wxSvgXmlAttrHash GetAttributes() const;
    virtual wxSVGDTD GetDtd() const { return wxSVG_SCRIPT_ELEMENT; }
};

#endif // WX_SVG_SCRIPT_ELEMENT_H
