//////////////////////////////////////////////////////////////////////////////
// Name:        SVGTRefElement.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_T_REF_ELEMENT_H
#define WX_SVG_T_REF_ELEMENT_H

#include "SVGTextPositioningElement.h"
#include "SVGURIReference.h"
#include "String_wxsvg.h"
#include "Element.h"

class wxSVGTRefElement:
  public wxSVGTextPositioningElement,
  public wxSVGURIReference
{
  public:
    wxSVGTRefElement(std::wstring tagName = _T("tref")):
      wxSVGTextPositioningElement(tagName) {}
    virtual ~wxSVGTRefElement() {}
    wxSvgXmlNode* CloneNode(bool deep = true) { return new wxSVGTRefElement(*this); }
    bool HasAttribute(const std::wstring& name);
    std::wstring GetAttribute(const std::wstring& name);
    bool SetAttribute(const std::wstring& name, const std::wstring& value);
    wxSvgXmlAttrHash GetAttributes() const;
    virtual wxSVGDTD GetDtd() const { return wxSVG_TREF_ELEMENT; }
};

#endif // WX_SVG_T_REF_ELEMENT_H
