//////////////////////////////////////////////////////////////////////////////
// Name:        SVGViewSpec.h
// Author:      Alex Thuering
// Copyright:   (c) 2005 Alex Thuering
// Licence:     wxWindows licence
// Notes:       generated by generate.py
//////////////////////////////////////////////////////////////////////////////

#ifndef WX_SVG_VIEW_SPEC_H
#define WX_SVG_VIEW_SPEC_H

class wxSVGElement;

#include "SVGZoomAndPan.h"
#include "SVGFitToViewBox.h"
#include "SVGTransformList.h"
#include "String_wxsvg.h"
#include "Element.h"

class wxSVGViewSpec:
  public wxSVGZoomAndPan,
  public wxSVGFitToViewBox
{
  protected:
    wxSVGTransformList m_transform;
    wxSVGElement* m_viewTarget;
    std::wstring m_viewBoxString;
    std::wstring m_preserveAspectRatioString;
    std::wstring m_transformString;
    std::wstring m_viewTargetString;

  public:
    inline const wxSVGTransformList& GetTransform() const { return m_transform; }
    inline void SetTransform(const wxSVGTransformList& n) { m_transform = n; }

    inline wxSVGElement* GetViewTarget() const { return m_viewTarget; }
    inline void SetViewTarget(wxSVGElement* n) { m_viewTarget = n; }

    inline const std::wstring& GetViewBoxString() const { return m_viewBoxString; }
    inline void SetViewBoxString(const std::wstring& n) { m_viewBoxString = n; }

    inline const std::wstring& GetPreserveAspectRatioString() const { return m_preserveAspectRatioString; }
    inline void SetPreserveAspectRatioString(const std::wstring& n) { m_preserveAspectRatioString = n; }

    inline const std::wstring& GetTransformString() const { return m_transformString; }
    inline void SetTransformString(const std::wstring& n) { m_transformString = n; }

    inline const std::wstring& GetViewTargetString() const { return m_viewTargetString; }
    inline void SetViewTargetString(const std::wstring& n) { m_viewTargetString = n; }

  public:
    wxSVGViewSpec(): m_viewTarget(NULL) {}
    virtual ~wxSVGViewSpec() {}
    bool HasAttribute(const std::wstring& name);
    std::wstring GetAttribute(const std::wstring& name);
    bool SetAttribute(const std::wstring& name, const std::wstring& value);
    wxSvgXmlAttrHash GetAttributes() const;
};

#endif // WX_SVG_VIEW_SPEC_H
